# Generated by Django 5.1.7 on 2025-03-19 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(verbose_name='количество в наличии')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'цветок',
                'verbose_name_plural': 'цветы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('status_order', models.CharField(choices=[('processing', 'в обработке'), ('shipped', 'отправлен'), ('delivered', 'доставлен'), ('canceled', 'отменен')], default='processing', max_length=20, verbose_name='статус заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая сумма')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.flowers', verbose_name='цветок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='почта')),
                ('password', models.CharField(max_length=255, verbose_name='пароль')),
                ('address', models.TextField(max_length=500, verbose_name='адрес доставки')),
            ],
            options={
                'verbose_name': 'пользователи',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='пользователь'),
        ),
    ]
