# Generated by Django 5.1.7 on 2025-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_flowers_order_ordertime_user_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='адрес доставки'),
        ),
    ]
