# Generated by Django 5.1.7 on 2025-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_options_flowers_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image_four',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Изображение4'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='image_three',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='image_two',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Изображение2'),
        ),
    ]
